### ISSUE TITLE
restore pypi release pypeline

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/tox-ansible#2]
Steps to do done:

* @geerlingguy to add `ssbarnea` and `ansible-community` as maintainers on PyPI in addition to his account (testpipy already done).
* someone with access to bot credentials should generate tokens for tox-ansible and configure it in secrets for `PYPI_PASSWORD` and `TESTPIPY_PASSWORD`.
* Update the setup.cfg metadata and check that a new pre-release is published correctly.

**Comment by greg-hellings** [comment]
I can add either @geerlingguy or @ssbarnea to tox-ansible as an owner in PyPI.

**Comment by ssbarnea** [comment]
@greg-hellings please also create an account `greg.hellings` for test.pypi.org - so I can add you as backup.

**Comment by greg-hellings** [comment]
Done. What are y'all's accounts on main?

**Comment by ssbarnea** [comment]
I still do not see multiple maintainers on https://pypi.org/project/tox-ansible/ -- but I fixed testpypi presence where now we have 3 owners and one bot maintainer, as future proof as it can be.

**Comment by greg-hellings** [comment]
I didn't know your accounts on there. You and gundalow should both be added as owners, now.

**Comment by ssbarnea** [comment]
As of today the release pipeline appears to be working fine.
